version: '3.4'

services:
  fomantic_build:
    build: external/fomantic
    command: gulp build
    volumes:
      - /fomantic/node_modules
      - ./blog/themes/shalom-olam-hugo-theme/static/css/semantic.rtl.min.css:/fomantic/dist/semantic.rtl.min.css
      - ./blog/themes/shalom-olam-hugo-theme/static/js/semantic.min.js:/fomantic/dist/semantic.min.js
      - ./blog/themes/shalom-olam-hugo-theme/static/css/themes:/fomantic/dist/themes
      - ./external/fomantic/semantic.json:/fomantic/semantic.json
      - ./external/fomantic/site:/fomantic/site
  
  package_dev:
    build: package
    command: npm run-script build
    volumes:
      - /package/node_modules
      - ./package:/package-