version: '3.4'

services:
  fomantic_build:
    build: external/fomantic
    command: gulp build
    volumes:
      - /fomantic/node_modules
      - ./external/fomantic/distribution/semantic.rtl.min.css:/fomantic/dist/semantic.rtl.min.css
      - ./external/fomantic/distribution/semantic.min.js:/fomantic/dist/semantic.min.js
      - ./external/fomantic/distribution/themes:/fomantic/dist/themes
      - ./external/fomantic/semantic.json:/fomantic/semantic.json
      - ./external/fomantic/site:/fomantic/site
  
  package_dev:
    build: package
    command: npm run-script build
    volumes:
      - /package/node_modules
      - /package/external
      - ./package:/package
      - ./external/fomantic/distribution:/package/external
      - ./blog/themes/shalom-olam-hugo-theme/static/js/main.js:/package/distribution/main.js