baseURL = "http://example.org/"
languageCode = "he-il"
title = "שלום עולם"

theme = "shalom-olam-hugo-theme"
summaryLength = 20
sectionPagesMenu = "main"

paginate = 3

[taxonomies]
    category = "categories"
    series = "series"